# Arduino Hardware

## Microcontollers
Microcontrollers are at the heart of many everyday electronic devices, from simple electronic toys to washing machines. But what is a microcontroller? Microcontrollers are best viewed as a miniature version of a home or office computer, they have a processing unit, various types of memory and methods for input and output. Compared to your computer though they may seem woefully under-powered. Take the Arduino Uno as an example, its processor runs at 16MHz rather than a couple of gigahertz, it has a flash memory of 32KB rather than several gigabytes. You may be surprised therefore to learn that microcontrollers are as popular as ever. The simple reason for this is that they are cheap and have a very low power consumption, and these two features make them suitable for a wide range of purposes. Low cost devices capable of computation, writing data to SD cards, and sharing data over a local network or the internet have huge potential for biological research. Being able to run such devices from batteries, linking to the world using mobile phone data connections or SMS could revolutionise ecological studies.

One of the advantages of using a microcontroller is that it is a multi-functional device, by writing a program to run on the microcontroller you can define what it does. The Arduino is an easily re-programmable microcontroller board that can be re-purposed using your computer and a USB cable. This makes an Arduino an incredibly useful piece of lab equipment. When it’s not being used as a temperature and humidity monitor alongside a malaise trap it can be used to monitor plant growth using an ultrasonic distance detector, or even act as a miniature web server. The alternative to a programmable microcontroller is learning what the vast array of individual integrated circuit chips each do, and painstakingly finding a way to get them to work together, for a single purpose. While this is still a useful skill for electronic engineers and hobbyists it is a daunting and time consuming new skill set for most biologists. The Arduino is intended to democratise access to microcontrollers, making their functionality available to interaction designers as well as artists and scientists. You will still need to learn some basics, but far less than you would need to know without the Arduino system.